#!/bin/bash

echo "=================================================="
echo "🚀 GitHub Repository Setup & Push"
echo "=================================================="
echo ""

echo "Step 1: Create GitHub Repository"
echo "--------------------------------"
echo "Go to: https://github.com/new"
echo ""
echo "Settings:"
echo "  Repository name: rtai-air-quality"
echo "  Description: Smart City Air Quality Monitoring with ML/DL"
echo "  Visibility: Public"
echo "  ❌ DON'T initialize with README, .gitignore, or license"
echo ""
echo "Click 'Create repository'"
echo ""

read -p "Press Enter after you've created the repository on GitHub..."

echo ""
echo "Step 2: Pushing to GitHub"
echo "--------------------------------"
echo ""

git push -u origin main

if [ $? -eq 0 ]; then
    echo ""
    echo "✅ Success! Code pushed to GitHub"
    echo ""
    echo "Your repository: https://github.com/Violetcv/rtai-air-quality"
    echo ""
    echo "=================================================="
    echo "Next: Deploy on Render"
    echo "=================================================="
    echo ""
    echo "1. Go to: https://render.com"
    echo "2. Click 'Get Started' or 'Sign In'"
    echo "3. Sign in with GitHub"
    echo "4. Click 'New +' → 'Web Service'"
    echo "5. Connect your repository: rtai-air-quality"
    echo "6. Use these settings:"
    echo "   - Name: rtai-air-quality"
    echo "   - Runtime: Python 3"
    echo "   - Build Command: pip install -r requirements.txt"
    echo "   - Start Command: gunicorn -b 0.0.0.0:\$PORT app:app --timeout 120 --workers 2"
    echo "   - Instance Type: Free"
    echo "7. Click 'Create Web Service'"
    echo ""
    echo "📖 Full instructions: Read RENDER_DEPLOY.md"
    echo "=================================================="
else
    echo ""
    echo "❌ Push failed. This might happen if:"
    echo "   1. Repository doesn't exist on GitHub yet"
    echo "   2. You need to authenticate"
    echo ""
    echo "To authenticate:"
    echo "   Go to: https://github.com/settings/tokens"
    echo "   Generate new token (classic)"
    echo "   Select 'repo' scope"
    echo "   Use token as password when prompted"
    echo ""
fi
